### PR TITLE
Return a static RegExp object instead

### PR DESCRIPTION
**Pull request by nc7s**
of a function that generates a new one every time called.

### CODE REVIEW

**Comment by juliangruber** [comment]
why?

there is state stored with a regexp, so it makes sense to get a new one each time

**Comment by tunnckoCore** [comment]
> why?

same here.

@zorceta it's like a convention for @regexhq organization. What's the case?

edit: And when you creates a PRs also update the tests, talking in general.

**Comment by jonschlinkert** [comment]
As @juliangruber points out, regexes sometimes store state. The convention of returning a function makes the API consistent so that implementors don't need to read the code to figure out if something is using the `g` flag or not, etc.

I'm going to go ahead and close, but we do appreciate you taking the time to do a pr

**Comment by nc7s** [comment]
Good point, did't recognize states can be stored in RegExp objects. Went from is-whitespace and saw its "caching", then did this. Sorry guys.

**Comment by jonschlinkert** [comment]
No worries! these discussions are how we learn (I think I learned in a similar way about regex state), don't ever feel sorry for contributing your time to open source!

**Pull request closed without merging**
